### ISSUE TITLE
Alert Silencing failing

### ISSUE THREAD

**Issue by jlark** [GreatLakesEnergy/sesh-dash-beta#170]
[2016-05-15 11:57:30,980: ERROR/MainProcess] Task seshdash.tasks.alert_engine[fe724624-ee5c-439e-aaee-5c162602781a] raised unexpected: AttributeError("'NoneType' object has no attribute 'minutes_last_contact'",)
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/celery/app/trace.py", line 240, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/celery/app/trace.py", line 438, in __protected_call__
    return self.run(*args, **kwargs)
  File "/home/dev/sesh-dash/src/seshdash/tasks.py", line 572, in alert_engine
    alert_status_check()
  File "/home/dev/sesh-dash/src/seshdash/utils/alert.py", line 325, in alert_status_check
    content = get_alert_content(site, rule, get_alert_point(alert), get_alert_point_value(alert), alert)
  File "/home/dev/sesh-dash/src/seshdash/utils/alert.py", line 290, in get_alert_point_value
    value = getattr(point, field_name)

**Comment by jlark** [comment]
Happens when no DP is returned for the site

[2016-05-15 11:57:26,091: WARNING/Worker-2] RMC STATUS: No DP found for site sesh_ep

**Comment by jlark** [comment]
This exception case should get handled so alert silencing does not' fail completely.

**Comment by jlark** [comment]
Looks like this is still an issue in production.
