### ISSUE TITLE
influx db connection causes 500 

### ISSUE THREAD

**Issue by jlark** [GreatLakesEnergy/sesh-dash-beta#206]
Traceback (most recent call last):
  File "/home/dev/sesh-dash/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/dev/sesh-dash/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/dev/sesh-dash/local/lib/python2.7/site-packages/django/contrib/auth/decorators.py", line 23, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/home/dev/sesh-dash/src/seshdash/views.py", line 96, in index
    measurements_value=client.get_measurements()
  File "/home/dev/sesh-dash/src/seshdash/data/db/influx.py", line 228, in get_measurements
    return list(self._influx_client.query(query,database=db).get_points())
  File "/home/dev/sesh-dash/local/lib/python2.7/site-packages/influxdb/client.py", line 307, in query
    expected_response_code=expected_response_code
  File "/home/dev/sesh-dash/local/lib/python2.7/site-packages/influxdb/client.py", line 223, in request
    raise e
ConnectionError: HTTPConnectionPool(host='sesh-dev1', port=8086): Max retries exceeded with url: /query?q=SHOW+measurements&db=sesh (Caused by NewConnectionError('<requests.packages.urllib3.connection.HTTPConnection object at 0x7f0c57733290>: Failed to establish a new connection: [Errno 111] Connection refused',))\

This should be handled.

**Comment by jlark** [comment]
@rawjazz @Frankkwizera can you guys sort this out?

**Comment by rawjazz** [comment]
ConnectionError: HTTPConnectionPool(host='sesh-dev1', port=8086):
do we have such a host('sesh-dev-1')??

**Comment by jlark** [comment]
it's sesh-dev1  not sesh-dev-1
Also how is it relevant?

**Comment by rawjazz** [comment]
that's mean that it was just a typo or it was working earlier?

**Comment by jlark** [comment]
The problem is not that the database is there or not. The problem is that the dashboard shouldn't break if the influx connection fails. It should get handled and maybe an error message is shown saying there is a problem with db connection.
