### ISSUE TITLE
logger not defined in settings.py

### ISSUE THREAD

**Issue by jlark** [GreatLakesEnergy/sesh-dash-beta#227]
}(sesh-dash) dev@sesh-dev1:~/sesh-dash/sesh-dash-beta$ python manage.py
Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/home/dev/sesh-dash/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 353, in execute_from_command_line
    utility.execute()
  File "/home/dev/sesh-dash/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 302, in execute
    settings.INSTALLED_APPS
  File "/home/dev/sesh-dash/local/lib/python2.7/site-packages/django/conf/__init__.py", line 55, in __getattr__
    self._setup(name)
  File "/home/dev/sesh-dash/local/lib/python2.7/site-packages/django/conf/__init__.py", line 43, in _setup
    self._wrapped = Settings(settings_module)
  File "/home/dev/sesh-dash/local/lib/python2.7/site-packages/django/conf/__init__.py", line 99, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/home/dev/sesh-dash/sesh-dash-beta/sesh/settings.py", line 92, in <module>
    logger.debug("No templates block in the settings local")
NameError: name 'logger' is not defined

How is this passing test not sure?

**Comment by upatricck** [comment]
I think i forgot to add the logger declarations, 

Not sure why the test are passing.

**Comment by upatricck** [comment]
It is because the exception is not thrown on the first local system and the testing system,

Fixing it.
