### ISSUE TITLE
Error while setting up

### ISSUE THREAD

**Issue by sbagri** [GreatLakesEnergy/sesh-dash-beta#320]
I followed the steps in https://github.com/GreatLakesEnergy/sesh-dash-beta#how-do-i-get-set-up-using-a-dev-vm
In step 9. Collect Static files in one place: $ python ./manage.py collectstatic
I am getting an error. The tail of the error is 

-------------
Found another file with the destination path 'django_extensions/img/indicator.gif'. It will be ignored since only the first encountered file is collected. If this is not what you want, make sure every static file has a unique path.
Traceback (most recent call last):
  File "./manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 353, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 345, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/base.py", line 348, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/base.py", line 399, in execute
    output = self.handle(*args, **options)
  File "/usr/local/lib/python2.7/dist-packages/django/contrib/staticfiles/management/commands/collectstatic.py", line 176, in handle
    collected = self.collect()
  File "/usr/local/lib/python2.7/dist-packages/django/contrib/staticfiles/management/commands/collectstatic.py", line 98, in collect
    for path, storage in finder.list(self.ignore_patterns):
  File "/usr/local/lib/python2.7/dist-packages/django/contrib/staticfiles/finders.py", line 112, in list
    for path in utils.get_files(storage, ignore_patterns):
  File "/usr/local/lib/python2.7/dist-packages/django/contrib/staticfiles/utils.py", line 28, in get_files
    directories, files = storage.listdir(location)
  File "/usr/local/lib/python2.7/dist-packages/django/core/files/storage.py", line 299, in listdir
    for entry in os.listdir(path):
OSError: [Errno 2] No such file or directory: '/home/vagrant/dev/sesh/components/components'
-------------

I am running this command in cygwin in windows7 machine
Any help would be greatly appreciated

**Comment by jlark** [comment]
hi @sbagri can you tell me how your project folder is structured?

**Comment by sbagri** [comment]
vagrant@vagrant-ubuntu-trusty-64:~/dev/sesh$ pwd
/home/vagrant/dev/sesh
vagrant@vagrant-ubuntu-trusty-64:~/dev/sesh$ ls
components       initial_data.json  logs       playbook.yml  requirements.txt  seshdash      sesh_dash_schema.dot  templates  Vagrantfile
drop_tables.sql  LICENSE            manage.py  README.md     sesh              sesh_dash.db  settings_local.ini    update.sh


Is this helpful?

**Comment by jlark** [comment]
Did you try creating the folder `/home/vagrant/dev/sesh/components/components` manually?

**Comment by sbagri** [comment]
No, let me try that

**Comment by sbagri** [comment]
Looks to work. However, I see a lot of warning type message. Copying the head here

vagrant@vagrant-ubuntu-trusty-64:~/dev/sesh$ python ./manage.py collectstatic

You have requested to collect static files at the destination
location as specified in your settings:

    /home/vagrant/dev/sesh/seshdash/static

This will overwrite existing files!
Are you sure you want to do this?

Type 'yes' to continue, or 'no' to cancel: yes
Found another file with the destination path 'admin/css/base.css'. It will be ignored since only the first encountered file is collected. If this is not what you want, make sure every static file has a unique path.
Found another file with the destination path 'admin/css/changelists.css'. It will be ignored since only the first encountered file is collected. If this is not what you want, make sure every static file has a unique path.

**Comment by jlark** [comment]
shouldn't be an issue.

**Comment by sbagri** [comment]
Ok, thanks a lot !!

**Comment by jlark** [comment]
Hi @sbagri,
Please keep in mind this is a work in progress and will require technical know how re django/celery and other components to get working correctly. Just so you know.

Thanks for checking it out.
All the best
