### ISSUE TITLE
issue with SMS sending for alerts.

### ISSUE THREAD

**Issue by jlark** [GreatLakesEnergy/sesh-dash-beta#335]
This is happening in PROD> It seems to happen when an alert is triggered

Task seshdash.tasks.alert_engine with id 5e936bee-4bdb-4e11-8263-24fd84734daa raised exception: “IndexError('list index out of range',)”

Task was called with args: [] kwargs: {}.

The contents of the full traceback was:

Traceback (most recent call last):

File "/usr/local/lib/python2.7/dist-packages/celery/app/trace.py", line 240, in trace_task
  R = retval = fun(*args, **kwargs)
File "/usr/local/lib/python2.7/dist-packages/celery/app/trace.py", line 438, in __protected_call__
  return self.run(*args, **kwargs)
File "/home/dev/sesh-dash/src/seshdash/tasks.py", line 597, in alert_engine
  alert_generator()
File "/home/dev/sesh-dash/src/seshdash/utils/alert.py", line 59, in alert_generator
  alert_obj.smsSent = send_sms(sms_numbers, content)
File "/home/dev/sesh-dash/src/seshdash/utils/send_sms.py", line 20, in send_sms
  response = clicksms.sendMessage(recipients, sms)
File "/home/dev/sesh-dash/local/lib/python2.7/site-packages/clickatell/rest/__init__.py", line 47, in sendMessage
  entry = self.merge({'apiMessageId': False, 'to': data['to'][0], 'error': False, 'errorCode': False}, entry)
IndexError: list index out of range

— Just to let you know, py-celery at celery@sesh-prod1.

**Comment by upatricck** [comment]
The response is [{'errorCode': '114', 'destination': '0785849636', 'id': '', 'error': 'Cannot route message'}] 

Clickatell is currently not routing messages. Checking it later.
