### ISSUE TITLE
TemplateSyntaxError: <class 'django.template.exceptions.TemplateSyntaxError'>

### ISSUE THREAD

**Issue by jlark** [GreatLakesEnergy/sesh-dash-beta#72]
View details in Rollbar: [https://rollbar.com/GLE/Sesh-dash/items/20/](https://rollbar.com/GLE/Sesh-dash/items/20/)

```
Traceback (most recent call last):
  File "c:\Users\alp\Desktop\dev\sesh-dash-env\lib\site-packages\django\core\handlers\base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "c:\Users\alp\Desktop\dev\sesh-dash-env\sesh-dash-beta\seshdash\views.py", line 242, in login_user
    return render(request,'seshdash/login.html')
  File "c:\Users\alp\Desktop\dev\sesh-dash-env\lib\site-packages\django\shortcuts.py", line 67, in render
    template_name, context, request=request, using=using)
  File "c:\Users\alp\Desktop\dev\sesh-dash-env\lib\site-packages\django\template\loader.py", line 96, in render_to_string
    template = get_template(template_name, using=using)
  File "c:\Users\alp\Desktop\dev\sesh-dash-env\lib\site-packages\django\template\loader.py", line 32, in get_template
    return engine.get_template(template_name, dirs)
  File "c:\Users\alp\Desktop\dev\sesh-dash-env\lib\site-packages\django\template\backends\django.py", line 40, in get_template
    return Template(self.engine.get_template(template_name, dirs), self)
  File "c:\Users\alp\Desktop\dev\sesh-dash-env\lib\site-packages\django\template\engine.py", line 190, in get_template
    template, origin = self.find_template(template_name, dirs)
  File "c:\Users\alp\Desktop\dev\sesh-dash-env\lib\site-packages\django\template\engine.py", line 157, in find_template
    name, template_dirs=dirs, skip=skip,
  File "c:\Users\alp\Desktop\dev\sesh-dash-env\lib\site-packages\django\template\loaders\base.py", line 46, in get_template
    contents, origin, origin.template_name, self.engine,
  File "c:\Users\alp\Desktop\dev\sesh-dash-env\lib\site-packages\django\template\base.py", line 189, in __init__
    self.nodelist = self.compile_nodelist()
  File "c:\Users\alp\Desktop\dev\sesh-dash-env\lib\site-packages\django\template\base.py", line 230, in compile_nodelist
    return parser.parse()
  File "c:\Users\alp\Desktop\dev\sesh-dash-env\lib\site-packages\django\template\base.py", line 514, in parse
    raise self.error(token, e)
TemplateSyntaxError: <class 'django.template.exceptions.TemplateSyntaxError'>
```

**Comment by jlark** [comment]
Need to disable rollbar in dev.
